package template

import (
	"bytes"
	"embed"
	"fmt"
	"go/format"
	"strconv"
	"strings"
	texttemplate "text/template"
)

const Disclaimer = "Code generated by gen. DO NOT EDIT."

//go:embed templates/*.tmpl
var templatesFS embed.FS

var templates = texttemplate.Must(texttemplate.New("").
	Funcs(texttemplate.FuncMap{
		"quote":     strconv.Quote,
		"sqlIdent":  sqlIdent,
		"sqlString": sqlString,
	}).
	ParseFS(templatesFS, "templates/*.tmpl"))

func Render(name string, data any) ([]byte, error) {
	var buf bytes.Buffer

	if err := templates.ExecuteTemplate(&buf, name, data); err != nil {
		return nil, fmt.Errorf("execute template %s: %w", name, err)
	}

	return buf.Bytes(), nil
}

func RenderGo(name string, data any) ([]byte, error) {
	result, err := Render(name, data)
	if err != nil {
		return nil, err
	}

	formatted, err := format.Source(result)
	if err != nil {
		return nil, fmt.Errorf("format generated go from %s: %w", name, err)
	}

	return formatted, nil
}

func sqlIdent(value string) string {
	return `"` + strings.ReplaceAll(value, `"`, `""`) + `"`
}

func sqlString(value string) string {
	return `'` + strings.ReplaceAll(value, `'`, `''`) + `'`
}
